_target_: src.models.seresnet50_module.SEResNet50LitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.00005
  weight_decay: 0.0

net:
  _target_: src.models.components.seresnet50.SEResNet50
  spatial_dims: 3
  in_channels: 1
  num_classes: 2
